### ISSUE TITLE
"apiServer is not defined" on file upload

### ISSUE THREAD

**Issue by montblanc13** [pCloud/pcloud-sdk-js#49]
## Context

Trying to upload file, after correcting error as [Issue #25](https://github.com/pCloud/pcloud-sdk-js/issues/25), I have now an error with a _apiServer is not defined_ error.

## The Code

This is the tested sample code : 

```
const pcloudSdk = require('pcloud-sdk-js');
const APP = require("../app.json");

const client = pcloudSdk.createClient(APP.access_token);
global.locationid = 1;

async function run2() {
    const fid = "12935045377";
    const file = "20220416170452_7a10e662c9c20bec86166d09.jpg";
    const res = await client.upload(file, fid);
    console.log(res);
}
run2().catch(error => console.error('Error', error));
```

## Execution and Error

```
Ξ Workspace git:(dev) ▶ node tests/pup.js
Error ReferenceError: apiServer is not defined
    at /xxx/node_modules/pcloud-sdk-js/lib/client/createClient.js:52:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run2 (/xxx/tests/pup.js:15:17)
```

Any  advice for helping ?

**Comment by montblanc13** [comment]
Sorry bad opening. 
The code is now working.
